global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'weather-api'
    static_configs:
      - targets: ['host.containers.internal:5221']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['host.containers.internal:9113']

  - job_name: 'traefik'
    static_configs:
      - targets: ['host.containers.internal:8081']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']

  - job_name: 'debezium'
    static_configs:
      - targets: ['host.containers.internal:9404']
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: /grafana/metrics

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
    metrics_path: /metrics

  - job_name: 'kratos'
    static_configs:
      - targets: ['host.containers.internal:4434']
    metrics_path: /admin/metrics/prometheus

  - job_name: 'minio'
    static_configs:
      - targets: ['host.containers.internal:9000']
    metrics_path: /minio/v2/metrics/cluster

  - job_name: 'podman'
    static_configs:
      - targets: ['host.containers.internal:9882']

  - job_name: 'blackbox-airflow'
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ['http://host.containers.internal:8280/airflow/health']
    static_configs:
      - targets: ['localhost:9115']
        labels:
          service: airflow
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: __param_target

  - job_name: 'blackbox-jupyter'
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ['http://host.containers.internal:8888/jupyter/api/status']
    static_configs:
      - targets: ['localhost:9115']
        labels:
          service: jupyter
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: __param_target
