FROM docker.io/apache/airflow:slim-2.10.4-python3.11
USER airflow
RUN pip install --no-cache-dir \
        apache-airflow-providers-common-sql \
        duckdb \
        duckdb-engine \
        minio \
        pandas \
        pyarrow \
        requests \
        "confluent-kafka[schema-registry]" \
        fastavro
COPY webserver_config.py /opt/airflow/webserver_config.py
COPY plugins/ /opt/airflow/plugins/
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
